# This file was generated by GoReleaser. DO NOT EDIT.
class RoboOkta < Formula
  desc "A CLI to automate cumbersome Okta UI tasks"
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/adisx06x/robo-okta/releases/download/v1.0.1/robo-okta_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "e66be0b3aa915c155d38ca4227d9a08bbd9e0109de4b171e14baccdffc52c4dd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/adisx06x/robo-okta/releases/download/v1.0.1/robo-okta_1.0.1_Linux_x86_64.tar.gz"
      sha256 "c19b124e21c58ecf476bd682a77bac7f0c318ec615b69fba9c96c3b08955da99"
    end
  end

  def install
    bin.install "robo-okta"
  end

  test do
    system "#{bin}/robo-okta version"
  end
end
