# This file was generated by GoReleaser. DO NOT EDIT.
class RoboOkta < Formula
  desc "A CLI to automate cumbersome Okta UI tasks"
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/adisx06x/robo-okta/releases/download/v1.0.1/robo-okta_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "37da890dee7c772adcd953aa7b97b9372af75a86b6bef0672f45e6994779ced7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/adisx06x/robo-okta/releases/download/v1.0.1/robo-okta_1.0.1_Linux_x86_64.tar.gz"
      sha256 "1dc6849b995bae0e65af733f923a32dc713fa6e9c1d6d8e8d625ee0270fbe65b"
    end
  end

  def install
    bin.install "robo-okta"
  end

  test do
    system "#{bin}/robo-okta version"
  end
end
